### ISSUE TITLE
Problems compiling master

### ISSUE THREAD

**Issue by arthuraa** [quadra-game/quadra#1]
If I try to compile Quadra@8b934ce232ec99f309c20f78028f87e263580745 using gcc 4.6 on Ubuntu, I get the following error:

```
In file included from include/net_stuff.h:24:0,
                 from include/chat_text.h:24,
                 from source/chat_text.cpp:21:
skelton/include/net.h:108:75: error: ‘NULL’ was not declared in this scope
skelton/include/net.h:250:56: error: ‘NULL’ was not declared in this scope
```

I was able to get it to work by adding `#include <stdlib.h>` to both `net.h` and `dict.h`. Since this seems only to be a mirror, I didn't want to send a pull request, but hope this helps anyway.

**Comment by pphaneuf** [comment]
I found your forked repository, and pull in both of your commits, as they seemed fine. I figure that GitHub is a better platform for something as lightly maintained, so that we can easily pull in contributions, so I decided to make it the official repository, after a few tweaks (the branch names were changed around).

Thanks!
